name: attendence
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_medium.ttf
        - asset: assets/fonts/montserrat_semibold.ttf
        - asset: assets/fonts/montserrat_regular.ttf

  assets:
    - assets/image/
    - assets/fonts/
    - assets/image/bg.jpg
    - assets/image/ahs_bk.png